services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
    # volumes:
    #   - ./config.py:/app/config.py  # For easier config updates

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "8501:8501"
    environment:
      - BACKEND_API_URL=http://backend:8080
    depends_on:
      - backend