apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-sage-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-sage-backend
  template:
    metadata:
      labels:
        app: stock-sage-backend
    spec:
      containers:
      - name: backend
        image: asia-south1-docker.pkg.dev/$PROJECT_ID/stock-analysis-agent/backend:v1
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: openai-api-key
        - name: TAVILY_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: tavily-api-key
        - name: LLM_MODEL
          value: "gpt-4o-mini"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: stock-sage-backend
spec:
  selector:
    app: stock-sage-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP